### ISSUE TITLE
Some questions about the code

### ISSUE THREAD

**Issue by Shaw95** [svip-lab/AS-MLP#6]
![image](https://user-images.githubusercontent.com/29199824/127726847-df0f11c4-bbce-43fb-817f-1ad29fefa5ac.png)
Hi, I have a few questions about the dimensions in yourt code.

- Is your input dimension format like B C H W, eg, 1, 3, 224, 224?
- If so, I suppose the dim in layernorm you initialized is C. when I run this, I got an error like
`Given normalized_shape=[2304], expected input with shape [*, 2304], but got input of size[8, 2304, 8, 8]`

- And also, how do you get the shape of `nW*B, window_size*window_size, C` after axis shift?

Thank you

**Comment by niujinshuchong** [comment]
@Shaw95 
1. Yes, the input has size [B, C, H, W].
2. We hack group norm to implement layer norm because the default pytorch layer norm only support channel dimension in the last dimension of the tensor. Please refer to https://github.com/svip-lab/AS-MLP/blob/main/models/as_mlp.py#L351
3. The comment is wrong. Sorry for the confusion. Will update it soon.

**Comment by Shaw95** [comment]
> @Shaw95
> 
> 1. Yes, the input has size [B, C, H, W].
> 2. We hack group norm to implement layer norm because the default pytorch layer norm only support channel dimension in the last dimension of the tensor. Please refer to https://github.com/svip-lab/AS-MLP/blob/main/models/as_mlp.py#L351
> 3. The comment is wrong and just updated. Sorry for the confusion.

Thanks
